"""add chat_messages table

Revision ID: 768fb1bf4808
Revises: edf38931b355
Create Date: 2026-07-29 23:08:48.993056

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "768fb1bf4808"
down_revision: str | None = "edf38931b355"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["resume_id"], ["resumes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_resume_id"), "chat_messages", ["resume_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_resume_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
